# Generated by Django 5.2.14 on 2026-07-10 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_review', '0001_initial'),
        ('resumes', '0002_resume_address_resume_certifications_resume_github_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('hiring_manager', models.CharField(blank=True, max_length=150)),
                ('key_skills', models.CharField(blank=True, max_length=255)),
                ('job_description', models.TextField()),
                ('letter_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
