# Generated by Django 5.2.14 on 2026-07-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(blank=True),
        ),
    ]
